database:
  host: localhost
  port: 5432
  user: your_user
  password: your_password
  dbname: attendance_db

  cache:
  host: localhost
  port: 6379

redis:
  host: "localhost"
  port: 6379
  db: 0
  password:
postgres:
  database: "your_database_name"
  user: "your_user"
  password: "your_password"
  host: "localhost"
  port: 5432

